config/routes.rb
Rails.application.routes.draw do
  root 'shop/main#index'

  get '/projects', to: 'projects#index'

  get '/blog', to: 'blog#index'
  get '/blog/:id', to: 'blog#show', as: 'post'

  get '/blog//tag/:id', to: 'blog#tag_show', as: 'tag'

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  mount Ckeditor::Engine => '/ckeditor'

  resources :news, :only => %w(index show)

  get 'contacts' => 'main#contacts'
  get 'bonus' => 'main#bonus'
  get 'cards' => 'main#cards'
  get 'actions' => 'main#actions'
  get 'public_offer' => 'main#public_offer'
  get 'delivery' => 'main#delivery'
  get 'payment' => 'main#payment'
  get '/admin/autocomplete_tags',
      to: 'admin/posts#autocomplete_tags',
      as: 'autocomplete_tags'

  namespace :gallery do
    root :to => 'main#index'
  end

  namespace :shop do
    root :to => 'main#index'
    get 'search', to: 'products#search'
    get 'autocomplete', to: 'products#autocomplete'
    resources :brands, only: %w(show)
    resources :categories, only: %w(index show) do
      resources :products, only: %w(index show)
    end

    scope :order do
      post ':product_id/add', to: 'order#add'
      post ':product_id/remove', to: 'order#remove'
      post ':product_id/update_count', to: 'order#update_count'
      post ':product_id/decrease', to: 'order#decrease'
      post ':product_id/update', to: 'order#update'
      post ':product_id/confirm', to: 'order#confirm'

      get 'show', to: 'order#show'
      get 'edit', to: 'order#edit'
      patch 'update', to: 'order#update'
      get 'confirm', to: 'order#confirm'
      post 'confirm', to: 'order#to_process'
      get :index
    end

  end



  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  namespace :profile do

    root :to => 'main#index'
    resources :orders, only: %w(index show)
    #     # Directs /admin_old/products/* to Admin::ProductsController
  end


  post 'exchange', to: 'exchange#exchange'
  get 'exchange', to: 'exchange#exchange'

  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :title, :description, :title_image

  has_attached_file :title_image,
                    :styles => {
                        :big => '600x600>',
                        :medium => "300x300>",
                        :thumb => "100x100>"
                    },
                    :default_url => ActionController::Base.helpers.asset_path("#{Rails.application.config.assets.prefix}/missing_:style.png")

  validates_attachment_content_type :title_image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/news_controller.rb
class NewsController < BaseController
  def index
    @news = News.paginate(:page => params[:page], :per_page => 30)
  end

  def show
    @news = News.find(params[:id])
  end
end

app/helpers/admin/news_helper.rb
module Admin::NewsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/index.html.erb
<% title 'События' %>
<div class="page-header white-page">
  <h1>События</h1>
</div>
<div class="row">

  <div class="col-xs-12 col-md-12">
    <% @news.each do |news| %>

        <div class="blog-post white">
          <div itemscope itemtype="http://schema.org/Article" class="media" style="vertical-align: baseline">
            <a class="pull-left" href="<%= news_url(news) %>">
              <%= image_tag news.title_image.url(:medium), itemprop: 'image'  %>
            </a>

            <div class="media-body">
              <h3 class="media-heading"><a href="<%= news_url(news.id)%>"> <span itemprop="name"><%= news.title %></span></a></h3>
              <p itemprop="articleBody"><%= truncate(strip_tags(news.description), :length => 250) %></p>

              <span itemprop="datePublished" content="2014-10-12" class="News Date"><%= Russian::strftime(news.created_at, "%d %b %Y") %></span>
            </div>
          </div>
        </div>
    <% end %>
  </div>
  <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
</div>

app/views/news/show.html.erb
<% title @news.title %>
<%# content_for :description, @post.small_description %>
<%# content_for :keywords, @post.small_description %>
<div class="page-header white-page">
  <h1 class="media-heading"><%= @news.title %> </h1>

</div>
<div class="row">
  <div class="col-xs-12">

    <div class="blog-post white">
      <div style="padding-bottom: 20px;">
        <div class="row">
          <div class="col-xs-12">
            <%= @news.description.html_safe %>
          </div>
        </div>
        <script type="text/javascript" src="//yandex.st/share/share.js"
                charset="utf-8"></script>
        <div style="float: right; " class="yashare-auto-init" data-yashareL10n="ru"
             data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir,gplus" data-yashareTheme="counter">

        </div>
      </div>
    </div>
  </div>
</div>