config/routes.rb
Rails.application.routes.draw do
  root 'shop/main#index'

  get '/projects', to: 'projects#index'

  get '/blog', to: 'blog#index'
  get '/blog/:id', to: 'blog#show', as: 'post'

  get '/blog//tag/:id', to: 'blog#tag_show', as: 'tag'

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  mount Ckeditor::Engine => '/ckeditor'

  resources :news, :only => %w(index show)

  get 'contacts' => 'main#contacts'
  get 'bonus' => 'main#bonus'
  get 'cards' => 'main#cards'
  get 'actions' => 'main#actions'
  get 'public_offer' => 'main#public_offer'
  get 'delivery' => 'main#delivery'
  get 'payment' => 'main#payment'
  get '/admin/autocomplete_tags',
      to: 'admin/posts#autocomplete_tags',
      as: 'autocomplete_tags'

  namespace :gallery do
    root :to => 'main#index'
  end

  namespace :shop do
    root :to => 'main#index'
    get 'search', to: 'products#search'
    get 'autocomplete', to: 'products#autocomplete'
    resources :brands, only: %w(show)
    resources :categories, only: %w(index show) do
      resources :products, only: %w(index show)
    end

    scope :order do
      post ':product_id/add', to: 'order#add'
      post ':product_id/remove', to: 'order#remove'
      post ':product_id/update_count', to: 'order#update_count'
      post ':product_id/decrease', to: 'order#decrease'
      post ':product_id/update', to: 'order#update'
      post ':product_id/confirm', to: 'order#confirm'

      get 'show', to: 'order#show'
      get 'edit', to: 'order#edit'
      patch 'update', to: 'order#update'
      get 'confirm', to: 'order#confirm'
      post 'confirm', to: 'order#to_process'
      get :index
    end

  end



  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  namespace :profile do

    root :to => 'main#index'
    resources :orders, only: %w(index show)
    #     # Directs /admin_old/products/* to Admin::ProductsController
  end


  post 'exchange', to: 'exchange#exchange'
  get 'exchange', to: 'exchange#exchange'

  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/product.rb
require 'elasticsearch/model'
class Product < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  belongs_to :category
  belongs_to :brand
  belongs_to :supplier

  before_destroy :save_product_names_for_orders

  has_many :order_items, dependent: :nullify
  has_many :specification_products
  has_many :specifications, :through => :specification_products

  accepts_nested_attributes_for :specifications, allow_destroy: true
  accepts_nested_attributes_for :specification_products, allow_destroy: true

  attr_accessible :name,
                  :price,
                  :description,
                  :category,
                  :category_id,
                  :title_image,
                  :brand,
                  :brand_id,
                  :site_url,
                  :article,
                  :product_code,
                  :supplier_id,
                  :rich_file_id,
                  :is_active,
                  :hight,
                  :width,
                  :len_metr,
                  :len_fut,
                  :count,
                  :rod_test,
                  :color,
                  :flavor,
                  :is_hit,
                  :is_sale,
                  :specification_ids,
                  :specification_products_attributes,
                  :fake_price,
                  :meta_keywords,
                  :meta_description,
                  :currency


  has_attached_file :title_image,
                    :styles => {
                        :big => '450x450>',
                        :medium => '300x300>',
                        :small => '170x170>',
                        :thumb => '100x100>'
                    },
                    :default_url => ActionController::Base.helpers.asset_path("#{Rails.application.config.assets.prefix}/missing_:style.png")

  validates_attachment_content_type :title_image, :content_type => /\Aimage\/.*\Z/

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :id,        type: 'long', index: :not_analyzed
      indexes :name,     analyzer: 'snowball'
      indexes :description,   analyzer: 'snowball'
      indexes :brand_id,   type: 'long', index: :not_analyzed, include_in_all: false
      indexes :category_id,   type: 'long', index: :not_analyzed, include_in_all: false
    end
  end

  def self.search(query)
    __elasticsearch__.search(
        {
            query: {
                multi_match: {
                    query: query,
                    fields: %w(name description brand.title category.title)
                }
            }
        }
    )
  end

  def as_indexed_json(options={})
    self.as_json(
      include: { category: { only: :title},
                 brand:  { only: :title}
      })
  end

  # after_save    { Indexer.perform_async(:index,  self.id) }
  # after_destroy { Indexer.perform_async(:delete, self.id) }

  private

  def save_product_names_for_orders
    self.order_items.update_all(product_name: self.name)
  end
end

app/controllers/shop/brands_controller.rb
class Shop::BrandsController < BaseController
  def show
    @products = Brand.find(params[:id]).all_products
  end
end

app/controllers/shop/categories_controller.rb
class CategoriesController < BaseController
  include TheSortableTreeController::Rebuild
  inherit_resources

  def manage
    @categories = Category.nested_set.select('id, title, parent_id').all
  end

  def index
    # redirect_to shop_category_products_url(Category.roots.first)
  end

  def show
    # redirect_to shop_category_products_url(params[:id])
  end
end

app/controllers/shop/main_controller.rb
class Shop::MainController < BaseController
  def index
    # @categoriest = Brand.all
  end
end

app/controllers/shop/order_controller.rb
class Shop::OrderController < BaseController

  before_filter :authenticate_user!, only: :index

  skip_before_filter :verify_authenticity_token, :only => %i(add remove update_count decrease)

  before_filter :get_order, except: %i(index)
  before_filter :get_count, :only => %i(add update_count decrease)
  before_filter :get_product, :only => %i(add remove update_count decrease)

  def index #архив
    @orders = current_or_guest_user.orders #todo: представления
  end

  def add

    @order.add_product(@product, @count)

    respond_to do |format|
      format.html {redirect_to action: :show, product_id: @product.id }
      format.js
    end

  end

  def remove
    @order.remove_product(@product)
    render action: :update_count
  end

  def update_count
    @order.update_product_count @product, @count
  end

  def decrease
    @order.decrease_product_count(@product, @count)
  end

  def show
    # unless user_signed_in?
    #   flash[:notice] = 'Для оформления заказа требуется авторизация'
    #   authenticate!
    # end
  end

  def edit
    @order.phone = current_or_guest_user.phone
    @order.fio = current_or_guest_user.fio
    @order.address = current_or_guest_user.address
  end

  def update
    @order.attributes = params[:order]
    @order.validate_contacts = true

    if @order.valid?
      @order.save
      redirect_to action: :confirm
    else
      render action: :edit
    end
  end

  def confirm

  end

  def to_process
    @order.set_confirmed_by_user
    if current_or_guest_user && current_or_guest_user.lazy_id.present?

      # user.destroy
      # session[:guest_user_id] = nil

      @pass = get_temp_password
      @test_u = User.find_by_email(@order.email)
      if @test_u.nil?
        @u = User.create(email: @order.email, :password => @pass, :fio => @order.fio, :address => @order.address, :phone => @order.phone )
        @u.save(validate: false)
      else
        @u = @test_u
      end

      @order.user = @u
      if @order.save!
        guest_user.destroy # Stuff have been handed over. Guest isn't needed anymore.
        cookies.delete :uuid # The cookie is also irrelevant now
        UserMailer.auto_registration_email(@u, @pass).deliver if @test_u.nil?
      end
      sign_in(:user, @u)
    end
    flash[:notice] = 'Ваш заказ оформлен. В ближайшее время с Вами свяжется наш менеджер'
    UserMailer.delay.order_notification(@order)
    UserMailer.delay.order_information(@order)
    redirect_to controller: 'shop/main', action: :index
  end

  private


  def get_temp_password
    o =  [('a'..'z'),('A'..'Z')].map{|i| i.to_a}.flatten
    (0...9).map{ o[rand(o.length)]  }.join

  end

  def get_order
    if current_or_guest_user.present?
      @order = current_or_guest_user.cart
    else
      @order = create_guest_user.cart
    end

  end

  def get_product
    @product = Product.find(params[:product_id])
  end

  def get_count
    @count = params[:count].present? ? params[:count].to_i : 1
  end
end

app/controllers/shop/products_controller.rb
class Shop::ProductsController < BaseController
  before_filter :get_category
  skip_before_filter  :get_category, :only => [:search, :autocomplete]

  def index
    if params[:brand_id]
      @products = Category.find(params[:category_id]).all_products.where(:brand_id => params[:brand_id]).paginate(:page => params[:page], :per_page => 30)

    else
      @products = Category.find(params[:category_id]).all_products.paginate(:page => params[:page], :per_page => 30)

    end
  end

  def search
    if params[:q].nil?
      @products = []
    else
      @products = Product.search(params[:q]).records.where('category_id IS NOT NULL').where(:is_active => true)
    end

  end

  def autocomplete
    render json: Product.search(params[:term]).records.where('category_id IS NOT NULL').where(:is_active => true).limit(10).map{ |x| {:label => x.name, :category => x.category.title}}
  end

  def show
    @product = Product.find(params[:id])
  end

  def get_category
    @category = Category.find(params[:category_id])
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/shop/brands_helper.rb
module Shop::BrandsHelper
end

app/helpers/shop/main_helper.rb
module Shop::MainHelper
end

app/helpers/shop/products_helper.rb
module Shop::ProductsHelper
end

app/views/shop/products/_product_list_view.html.erb
<div class="panel panel-default product-panel">
  <div class="panel-body">
<!--<div class="row product_list_item">-->
<div class="row" prd ='prd'>
  <div class="col-xs-4 col-sm-5 col-md-3">
    <%= link_to image_tag(product_list_view.title_image.url(:small)), shop_category_product_url(product_list_view.category, product_list_view   ) %>
  </div>
  <div class="col-xs-6 col-sm-5 col-md-7">
    <h4><%= link_to product_list_view.name, shop_category_product_url(product_list_view.category, product_list_view   ) %> </h4>
    <p >
      Производитель: <%= link_to product_list_view.brand.title, shop_brand_url(product_list_view.brand) if product_list_view.brand%>
      <%= truncate(product_list_view.description.html_safe, :length => 250) if product_list_view.description %>
    </p>
  </div>
  <div class="col-xs-2 col-sm-2 col-md-2">
    <p class="pull-right" ><%= calculate_count(product_list_view.count.to_i) %></p>
    <div class="clearfix"></div>
    <h2 class="pull-right"><%= price_render product_list_view %> <small class='rub'>P</small> </h2><br/>
    <% if !product_list_view.count.present? || product_list_view.count == 0 %>
        <%= button_to 'Заказать', {controller: 'shop/order', action: :add, product_id: product_list_view.id}, {remote: true, method: :post, class: 'btn btn-danger pull-right add-to-cart'} %>
    <% else %>
        <%= button_to 'Купить', {controller: 'shop/order', action: :add, product_id: product_list_view.id}, {remote: true, method: :post, class: 'btn btn-success pull-right add-to-cart'} %><br/>
    <% end %>


  </div>

</div>
</div>
</div>

app/views/shop/products/_tiles_product_view.html.erb
<div prd ='prd' class="product product-<%= tiles_product_view.id %> prd col-xs-12 col-sm-6 col-lg-4 col-md-4" style="float: left">

  <div itemscope itemtype="http://schema.org/Product"  class="thumbnail box-shadow-inset product-block">
    <div class="caption">
      <h5><a href="<%= shop_category_product_url(tiles_product_view.category, tiles_product_view   ) %>"> <span itemprop="name"><%= tiles_product_view.name %></span></a> </h5>
    </div>
    <%= link_to image_tag(tiles_product_view.title_image.url(:small), itemprop: 'image'), shop_category_product_url(tiles_product_view.category, tiles_product_view   ) %>

    <div class="contenthover contenthover-<%= tiles_product_view.id %>">
      <div class="row">
        <div class="col-xs-12 col-sm-12">
          <a href="#" class="btn btn-default pull-left hidden-xs" data-toggle="modal" data-target="#productModal-<%= tiles_product_view.id %>" >Просмотр</a>
          <% if !tiles_product_view.count.present? || tiles_product_view.count == 0 %>
              <%= button_to 'Заказать', {controller: 'shop/order', action: :add, product_id: tiles_product_view.id}, {remote: true, method: :post, class: 'btn btn-danger pull-right add-to-cart'} %>
          <% else %>
              <%= button_to 'Купить', {controller: 'shop/order', action: :add, product_id: tiles_product_view.id}, {remote: true, method: :post, class: 'btn btn-success pull-right add-to-cart'} %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="caption tiles_bottom" >
      <% if tiles_product_view.brand.present? %>
      <div class="row">
        <div class="col-xs-6"><b class="pull-left">Производитель:</b></div>

        <div class="col-xs-6">
          <p class="pull-right">
          <% if tiles_product_view.brand%>
            <a itemprop="brand" itemscope itemtype="http://schema.org/Brand" class="pull-left" href="<%= shop_brand_url(tiles_product_view.brand) %>"> <span itemprop="name"><%= tiles_product_view.brand.title %></span></a>
          <% end %>
          </p>
        </div>
      </div>
      <% end %>

      <div class="row">
        <div class="col-xs-6">
          <b class="pull-left" style="color: red">
            <% if !tiles_product_view.count.present? || tiles_product_view.count == 0 %>
              Под заказ
            <% end %>
          </b>
        </div>

        <div class="col-xs-6"><p class="pull-right"><%= calculate_count(tiles_product_view.count.to_i) %></p></div>
      </div>

      <div class="row">
        <div class="col-xs-12"><h4 style=" float: right;"><%= price_render tiles_product_view %> <small class='rub'>P</small></h4></div>

       </div>
    </div>
  </div>

</div>

<div class="modal fade product" id="productModal-<%= tiles_product_view.id %>" tabindex="-1" role="dialog" aria-labelledby="productModalLabel-<%= tiles_product_view.id %>" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="loginModalLabel"><%= link_to tiles_product_view.name, shop_category_product_url(tiles_product_view.category, tiles_product_view   ) %></h4>
      </div>
      <div prd ='prd'  class="modal-body">
        <div class="row">
          <div class="col-sm-5 col-xs-12">
            <%= link_to image_tag(tiles_product_view.title_image.url(:medium)), shop_category_product_url(tiles_product_view.category, tiles_product_view   )  %>
          </div>

          <div class="col-sm-7 col-xs-12">
            <div class="caption">
              <div class="row">
                <div class="col-xs-6">
                  <h2 class="pull-left">
                    <%= price_render tiles_product_view %><small class='rub'>P</small></h2>
                </div>
                <div class="col-xs-6">
                  <h2 class="pull-right">
                    <% if !tiles_product_view.count.present? || tiles_product_view.count == 0 %>
                        <%= button_to 'Заказать', {controller: 'shop/order', action: :add, product_id: tiles_product_view.id}, {remote: true, method: :post, class: 'btn btn-danger pull-right add-to-cart'} %>
                    <% else %>
                        <%= button_to 'Купить', {controller: 'shop/order', action: :add, product_id: tiles_product_view.id}, {remote: true, method: :post, class: 'btn btn-success pull-right add-to-cart'} %>
                    <% end %>
                  </h2>
                </div>
              </div>



            </div>
            <div class="row">
              <div class="col-xs-12">
                <%= calculate_count(tiles_product_view.count.to_i) %>
              </div>
            </div>
            <% if tiles_product_view.category.present? && tiles_product_view.category.title.present? %>
                <div class="row">
                  <div class="col-xs-12">
                <b>Категория -</b> <%= link_to tiles_product_view.category.title, shop_category_products_url(tiles_product_view.category) %>
                  </div>
                </div>
            <% end %>
            <% if tiles_product_view.brand.present? && tiles_product_view.brand.title.present? %>
                <div class="row">
                  <div class="col-xs-12">
                <b>Производитель -</b> <%= link_to tiles_product_view.brand.title, shop_brand_url(tiles_product_view.brand) %>
                  </div>
                </div>
            <% end %>

            <% if tiles_product_view.article.present? %>
                <div class="row">
                  <div class="col-xs-12">
                    <b>Артикул -</b> <%= tiles_product_view.article %>
                  </div>
                </div>
            <% end %>
            <br/>
            <% if tiles_product_view.description.present? %>
                <div class="row">
                  <div class="col-xs-12">
                    <%= tiles_product_view.description.html_safe %>
                  </div>
                </div>
            <% end %>

            <% if tiles_product_view.specification_products.present? && tiles_product_view.specification_products.size > 0     %>
                <div class="page-header">
                  <h4>Технические характеристики</h4>

                </div>
                <% tiles_product_view.specification_products.each do |specification| %>
                    <div class="row">
                      <div class="col-xs-12">
                        <b><%= specification.specification.name if specification.specification.present? %></b> &mdash; <%= specification.value %><%= specification.specification.units if specification.specification.present?%>
                      </div>
                    </div>
                <% end %>
            <% end %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/shop/products/index.html.erb
<% title @category.parent.present? ? "#{@category.parent.title} - #{@category.title}" : @category.title %>
<% description  @category.meta_description %>
<% keywords @category.meta_keywords %>
<div class="row row-offcanvas row-offcanvas-right">

  <div role="navigation" id="sidebar" class="col-xs-4 col-sm-3 col-md-2 col-lg-2 sidebar-offcanvas hidden-xs">
    <%= render_navigation(:context => :main, :level => 2..4, :expand_all => true, :skip_if_empty => true) %>
  </div>
  <!--/span-->


  <div id="product-list" class="col-xs-12 col-sm-9 col-lg-10 col-md-10">


    <div class="page-header" style="margin: 0 0 20px;">
      <div class="row">

        <div class="col-xs-4 col-sm-6 col-lg-8 col-md-8">
          <%= form_tag shop_search_url, method: :get, :role => 'search', :id => 'search-form' do %>
              <div class="input-group">
                <%= text_field_tag :q, params[:q], :class => 'form-control search', :placeholder => 'Поиск' %>
                <span class="input-group-btn">
                    <%= submit_tag 'Найти', name: nil, :class => 'btn btn-default fishpassion' %>
                </span>
              </div>
          <% end %>
        </div>

        <div class="col-xs-3 col-sm-3 col-lg-2 col-md-2">
          <div class="dropdown pull-left ">
            <button class="btn btn-default dropdown-toggle fishpassion" type="button" id="brand_menu" data-toggle="dropdown">
              <%= params[:brand_id].present? ? Brand.find(params[:brand_id]).title : 'Все бренды' %>
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu fishpassion" role="menu" aria-labelledby="brand_menu">
              <li role="presentation">
                <a role="menuitem" tabindex="-1" href="<%= shop_category_products_url(params[:category_id], view: params[:view]) %>">Все
                  бренды</a></li>
              <% @brands.each do |brand| %>
                  <li role="presentation">
                    <a role="menuitem" tabindex="-1" href="<%= shop_category_products_url(params[:category_id], brand_id: brand.id, view: params[:view]) %>"><%= brand.title %></a>
                  </li>
                  <!--<li role="presentation"><a role="menuitem" tabindex="-1" href="?brand_id=<%#= brand.id %>"><%#= brand.title %></a></li>-->
              <% end %>

            </ul>
          </div>
        </div>

        <div class="col-xs-5 col-sm-3 col-lg-2 col-md-2">
          <div class="btn-group pull-right">
            <a title="Просмотр списком" href="<%= shop_category_products_url(params[:category_id], brand_id: params[:brand_id], view: 'list') %>" class="btn btn-default glyphicon glyphicon-th-list <%= params[:view] == 'list' ? 'active' : '' %> fishpassion"></a>
            <a title="Просмотр плиткой" href="<%= shop_category_products_url(params[:category_id], brand_id: params[:brand_id]) %>" class="btn btn-default glyphicon glyphicon-th-large <%= params[:view] == 'list' ? '' : 'active' %> fishpassion"></a>
          </div>
        </div>
        <!--</div>-->
      </div>


    </div>
    <% if @category.description.present? %>
        <div class="row">
          <div class="col-xs-12">
            <div class="panel panel-default">
              <div class="panel-body">
                <%= @category.description.html_safe %>
              </div>
            </div>
          </div>
        </div>
    <% end %>
    <% if params[:view] == 'list' %>
        <%= render :partial => 'product_list_view', :collection => @products %>
    <% else %>
        <%= render :partial => 'tiles_product_view', :collection => @products %>
    <% end %>

  </div>
  <!--/span-->
  <%= will_paginate @products, renderer: BootstrapPagination::Rails %>

</div>

<div><%= sape_links(2) %></div>

app/views/shop/products/search.html.erb
<% title 'Результаты поиска' %>
<div class="row row-offcanvas row-offcanvas-right">

  <div role="navigation" id="sidebar" class="col-xs-4 col-sm-3 col-md-2 col-lg-2 sidebar-offcanvas hidden-xs">
    <%= render_navigation(:context => :main, :level => 2..4, :expand_all => true, :skip_if_empty => true) %>
  </div>
  <!--/span-->



  <div id="product-list" class="col-xs-12 col-sm-9 col-lg-10 col-md-10">


    <div class="page-header" style="margin: 0 0 20px;">
      <div class="row">
        <div class="col-xs-7 col-sm-9 col-lg-10 col-md-10">
          <%= form_tag shop_search_url, method: :get, :role => 'search', :id => 'search-form' do %>
              <div class="input-group">
                <%= text_field_tag :q, params[:q], :class => 'form-control search', :placeholder => 'Поиск' %>
                <span class="input-group-btn">
                    <%= submit_tag 'Найти', name: nil, :class => 'btn btn-default fishpassion' %>
                </span>
              </div>
          <% end %>
        </div>
        <div class="col-xs-5 col-sm-3 col-lg-2 col-md-2">
          <div class="btn-group pull-right">
            <a title="Просмотр списком" href="<%= shop_search_url(q: params[:q], view: 'list') %>" class="btn btn-default glyphicon glyphicon-th-list <%= params[:view] == 'list'? 'active': '' %> fishpassion"></a>
            <a title="Просмотр плиткой" href="<%= shop_search_url(q: params[:q]) %>" class="btn btn-default glyphicon glyphicon-th-large <%= params[:view] == 'list'? '': 'active' %> fishpassion"></a>
          </div>
        </div>
        <!--</div>-->
      </div>

    </div>

    <% if params[:view] == 'list' %>
        <%= render :partial => 'product_list_view', :collection => @products %>
    <% else %>
        <%= render :partial => 'tiles_product_view', :collection => @products %>
    <% end %>

  </div>
  <!--/span-->
  <%#= will_paginate @products, renderer: BootstrapPagination::Rails %>

</div>

app/views/shop/products/show.html.erb
<% title @product.name %>
<% description  @product.meta_description %>
<% keywords @product.meta_keywords %>
<div itemscope itemtype="http://schema.org/Product">
<div class="page-header white-page">
  <h1 itemprop="name"><%= @product.name %> <small><script type="text/javascript" src="//yandex.st/share/share.js"
                                                          charset="utf-8"></script>
    <div style="float: right; " class="yashare-auto-init" data-yashareL10n="ru"
         data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir,gplus" data-yashareTheme="counter">

    </div></small></h1>
</div>

  <ol class="breadcrumb">
    <li><%= link_to 'Карпфишинг', shop_category_products_url(Category.roots.first) %></li>

    <% if @product.category.parent.present? && @product.category.parent.parent.present? %>
        <li><%= link_to @product.category.parent.title, shop_category_products_url(@product.category.parent) %></li>
    <% end %>

    <li><%= link_to @product.category.title, shop_category_products_url(@product.category) %></li>
    <li class="active"><%= @product.name %></li>

  </ol>

<div prd ='prd' class="product--panel" style="padding: 10px;">
  <div class="row">
    <div  class="col-sm-5 col-md-6col-md-4 popup-gallery">
      <a href="<%= image_url @product.title_image.url(:original) %>" class="thumbnail" data-title="<%= @product.name %>" >
      <%= image_tag @product.title_image.url(:big), itemprop: 'image'    %>
      </a>
    </div>
    <div class="col-sm-7 col-md-6">
          <div class="caption">
            <h2 itemprop="offers" itemscope itemtype="http://schema.org/Offer"> <span itemprop="price"><%= price_render @product %></span>
                <small class='rub'>P</small>
              <% if !@product.count.present? || @product.count == 0 %>
                  <%= link_to 'Заказать', {controller: 'shop/order', action: :add, product_id: @product.id}, {remote: true, method: :post, class: 'btn btn-danger pull-right add-to-cart'} %>
              <% else %>
                  <%= link_to 'Купить', {controller: 'shop/order', action: :add, product_id: @product.id}, {remote: true, method: :post, class: 'btn btn-success pull-right add-to-cart'} %>
              <% end %>
            </h2>
          </div>

      <div class="row">
        <div class="col-xs-12">
          <b>Наличие -</b> <%= calculate_count(@product.count.to_i) %>
        </div>
      </div>
      <% if @product.category.present? && @product.category.title.present? %>
          <div class="row">
            <div class="col-xs-12">
              <b>Категория -</b> <%= link_to @product.category.title, shop_category_products_url(@product.category) %>
            </div>
          </div>
      <% end %>
      <% if @product.brand.present? && @product.brand.title.present? %>
          <div class="row">
            <div class="col-xs-12">
              <b>Производитель -</b>
              <a itemprop="brand" itemscope itemtype="http://schema.org/Brand" href="<%= shop_brand_url(@product.brand) %>"> <span itemprop="name"><%= @product.brand.title %></span></a>
            </div>
          </div>
      <% end %>

      <% if @product.article.present? %>
          <div class="row">
            <div class="col-xs-12">
              <b>Артикул -</b> <%= @product.article %>
            </div>
          </div>
      <% end %>
      <br/>
      <% if @product.description.present? %>
          <div class="row">
            <div class="col-xs-12">
              <%= @product.description.html_safe %>
            </div>
          </div>
      <% end %>

      <% if @product.specification_products.present? && @product.specification_products.size > 0     %>
          <span itemprop="description">
          <div class="page-header">
            <h4>Технические характеристики</h4>

          </div>
          <% @product.specification_products.each do |specification| %>
              <div class="row">
                <div class="col-xs-12">
                  <b><%= specification.specification.name %></b> &mdash; <%= specification.value %><%= specification.specification.units if specification.specification.units %>
                </div>
              </div>
          <% end %>
          </span>
      <% end %>

    </div>
  </div>
</div>
</div>

<div><%= sape_links(3) %></div>